create table public.food_database (
  id bigint generated by default as identity primary key,
  food text not null,

  serving_size numeric(8,2) default 1 not null,
  serving_unit public.food_serving_unit
    default 'serving'::public.food_serving_unit not null,

  calories_kcal numeric(8,2) not null,
  protein_g numeric(8,2) not null,
  carbs_g numeric(8,2) not null,
  fat_g numeric(8,2) not null,
  fiber_g numeric(8,2) not null,
  sugar_g numeric(8,2) not null,

  date date not null default current_date
);

create index food_database_food_idx
on public.food_database using gin (
  to_tsvector('english', food)
);

------------------------------------------------------

-- ---------------- food_database ----------------

ALTER TABLE public.food_database ENABLE ROW LEVEL SECURITY;

CREATE POLICY "food_database_select_authenticated"
ON public.food_database
FOR SELECT
TO authenticated
USING (true);
