-------------------------------------------------------------------)
create table public.feedback (
  feedback_id bigint generated by default as identity not null,
  user_id uuid not null,
  created_at timestamp with time zone not null default now(),
  feedback_type text not null,
  subject text not null,
  description text not null,
  contact text null,
  email text null,
  allow_contact boolean not null default false,
  constraint feedback_pkey primary key (feedback_id),
  constraint feedback_user_id_fkey foreign key (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

-- Pre-insert command (feedback_id's based on type int)
ALTER TABLE public.feedback
ALTER COLUMN feedback_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (feedback_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.feedback', 'feedback_id'),
    (SELECT MAX(feedback_id) FROM public.feedback),
    true
);

-------------------------------------------------------------------
create table public.food (
  food_id bigint generated by default as identity not null,
  user_id uuid not null,
  description text not null,
  protein numeric(8, 2) not null default 0,
  fat numeric(8, 2) not null default 0,
  carb numeric(8, 2) not null default 0,
  calories_extra numeric(8, 2) not null default 0,
  my_food boolean not null default true,
  favorite_food boolean not null default false,
  share_with_others boolean not null default false,
  serving_size numeric(8, 2) not null default 1,
  serving_unit text not null,
  -- serving_unit public.food_serving_unit not null default 'serving'::food_serving_unit,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint food_pkey primary key (food_id),
  constraint food_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint food_carb_check check ((carb >= (0)::numeric)),
  constraint food_fat_check check ((fat >= (0)::numeric)),
  constraint food_calories_extra_check check ((calories_extra >= (0)::numeric)),
  constraint food_protein_check check ((protein >= (0)::numeric)),
  constraint food_serving_size_check check ((serving_size > (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists food_user_id_idx on public.food using btree (user_id) TABLESPACE pg_default;

create index IF not exists food_active_idx on public.food using btree (is_active) TABLESPACE pg_default;


-- Pre-insert command (food_id's based on type int)
ALTER TABLE public.food
ALTER COLUMN food_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (food_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.food', 'food_id'),
    (SELECT MAX(food_id) FROM public.food),
    true
);

-------------------------------------------------------------------
create table public.food_log (
  food_log_id bigint generated by default as identity not null,
  food_id bigint not null,
  user_id uuid not null,
  servings numeric(8, 2) not null default 1,
  datetime timestamp with time zone not null default now(),
  constraint food_log_pkey1 primary key (food_log_id),
  constraint food_log_food_id_fkey1 foreign KEY (food_id) references food (food_id) on delete CASCADE,
  constraint food_log_user_id_fkey1 foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint food_log_servings_check1 check ((servings > (0)::numeric))
) TABLESPACE pg_default;


-- Pre-insert command (food_log_id's based on type int)
ALTER TABLE public.food_log
ALTER COLUMN food_log_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (food_log_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.food_log', 'food_log_id'),
    (SELECT MAX(food_log_id) FROM public.food_log),
    true
);
-------------------------------------------------------------------
create table public.profile (
  profile_id bigint generated by default as identity not null,
  user_id uuid not null,
  fname text NOT NULL DEFAULT '',
  lname text NOT NULL DEFAULT '',
  sex text NOT NULL DEFAULT 'M',
  age integer CHECK (age IS NULL OR age >= 0),
  height numeric(6, 2) null,
  start_weight numeric(6, 2) null,
  goal_weight numeric(6, 2) null,
  activity_level text not null,
  daily_calorie_deficit integer not null default 0,
  diet_type text not null,
  sunday_protein numeric(5, 2) null,
  sunday_carbs numeric(5, 2) null,
  sunday_fat numeric(5, 2) null,
  monday_protein numeric(5, 2) null,
  monday_carbs numeric(5, 2) null,
  monday_fat numeric(5, 2) null,
  tuesday_protein numeric(5, 2) null,
  tuesday_carbs numeric(5, 2) null,
  tuesday_fat numeric(5, 2) null,
  wednesday_protein numeric(5, 2) null,
  wednesday_carbs numeric(5, 2) null,
  wednesday_fat numeric(5, 2) null,
  thursday_protein numeric(5, 2) null,
  thursday_carbs numeric(5, 2) null,
  thursday_fat numeric(5, 2) null,
  friday_protein numeric(5, 2) null,
  friday_carbs numeric(5, 2) null,
  friday_fat numeric(5, 2) null,
  saturday_protein numeric(5, 2) null,
  saturday_carbs numeric(5, 2) null,
  saturday_fat numeric(5, 2) null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint profile_pkey primary key (profile_id),
  constraint profile_user_id_key unique (user_id),
  constraint profile_user_fk foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint profile_friday_protein_check check (
    (
      (friday_protein >= (0)::numeric)
      and (friday_protein <= (100)::numeric)
    )
  ),
  constraint profile_goal_weight_check check ((goal_weight >= (0)::numeric)),
  constraint profile_height_check check ((height >= (0)::numeric)),
  constraint profile_monday_carbs_check check (
    (
      (monday_carbs >= (0)::numeric)
      and (monday_carbs <= (100)::numeric)
    )
  ),
  constraint profile_monday_fat_check check (
    (
      (monday_fat >= (0)::numeric)
      and (monday_fat <= (100)::numeric)
    )
  ),
  constraint profile_monday_protein_check check (
    (
      (monday_protein >= (0)::numeric)
      and (monday_protein <= (100)::numeric)
    )
  ),
  constraint profile_saturday_carbs_check check (
    (
      (saturday_carbs >= (0)::numeric)
      and (saturday_carbs <= (100)::numeric)
    )
  ),
  constraint profile_saturday_fat_check check (
    (
      (saturday_fat >= (0)::numeric)
      and (saturday_fat <= (100)::numeric)
    )
  ),
  constraint profile_saturday_protein_check check (
    (
      (saturday_protein >= (0)::numeric)
      and (saturday_protein <= (100)::numeric)
    )
  ),
  constraint profile_start_weight_check check ((start_weight >= (0)::numeric)),
  constraint profile_sunday_carbs_check check (
    (
      (sunday_carbs >= (0)::numeric)
      and (sunday_carbs <= (100)::numeric)
    )
  ),
  constraint profile_sunday_fat_check check (
    (
      (sunday_fat >= (0)::numeric)
      and (sunday_fat <= (100)::numeric)
    )
  ),
  constraint profile_sunday_protein_check check (
    (
      (sunday_protein >= (0)::numeric)
      and (sunday_protein <= (100)::numeric)
    )
  ),
  constraint profile_thursday_carbs_check check (
    (
      (thursday_carbs >= (0)::numeric)
      and (thursday_carbs <= (100)::numeric)
    )
  ),
  constraint profile_thursday_fat_check check (
    (
      (thursday_fat >= (0)::numeric)
      and (thursday_fat <= (100)::numeric)
    )
  ),
  constraint profile_thursday_protein_check check (
    (
      (thursday_protein >= (0)::numeric)
      and (thursday_protein <= (100)::numeric)
    )
  ),
  constraint profile_tuesday_carbs_check check (
    (
      (tuesday_carbs >= (0)::numeric)
      and (tuesday_carbs <= (100)::numeric)
    )
  ),
  constraint profile_tuesday_fat_check check (
    (
      (tuesday_fat >= (0)::numeric)
      and (tuesday_fat <= (100)::numeric)
    )
  ),
  constraint profile_tuesday_protein_check check (
    (
      (tuesday_protein >= (0)::numeric)
      and (tuesday_protein <= (100)::numeric)
    )
  ),
  constraint profile_wednesday_carbs_check check (
    (
      (wednesday_carbs >= (0)::numeric)
      and (wednesday_carbs <= (100)::numeric)
    )
  ),
  constraint profile_wednesday_fat_check check (
    (
      (wednesday_fat >= (0)::numeric)
      and (wednesday_fat <= (100)::numeric)
    )
  ),
  constraint profile_daily_calorie_deficit_check check ((daily_calorie_deficit >= 0)),
  constraint profile_wednesday_protein_check check (
    (
      (wednesday_protein >= (0)::numeric)
      and (wednesday_protein <= (100)::numeric)
    )
  ),
  constraint profile_friday_carbs_check check (
    (
      (friday_carbs >= (0)::numeric)
      and (friday_carbs <= (100)::numeric)
    )
  ),
  constraint profile_friday_fat_check check (
    (
      (friday_fat >= (0)::numeric)
      and (friday_fat <= (100)::numeric)
    )
  )
) TABLESPACE pg_default;


-- Pre-insert command (profile_id's based on type int)
ALTER TABLE public.profile
ALTER COLUMN profile_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (profile_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.profile', 'profile_id'),
    (SELECT MAX(profile_id) FROM public.profile),
    true
);

-------------------------------------------------------------------
create table public.supplement (
  supplement_id bigint generated by default as identity not null,
  user_id uuid not null,
  description text not null,
  serving_size numeric(8, 2) not null default 1,
  serving_unit text not null default 'other',
  share_with_others boolean not null default false,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint supplement_pkey primary key (supplement_id),
  constraint supplement_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint supplement_serving_size_check check ((serving_size > (0)::numeric))
) TABLESPACE pg_default;




-- Pre-insert command (supplement_id's based on type int)
ALTER TABLE public.supplement
ALTER COLUMN supplement_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (supplement_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.supplement', 'supplement_id'),
    (SELECT MAX(supplement_id) FROM public.supplement),
    true
);

-------------------------------------------------------------------
create table public.supplement_log (
  supplement_log_id bigint generated by default as identity not null,
  supplement_id bigint not null,
  user_id uuid not null,
  servings numeric(8, 2) not null default 1,
  date date not null default CURRENT_DATE,
  constraint supplement_log_pkey primary key (supplement_log_id),
  constraint supplement_log_supplement_id_fkey foreign KEY (supplement_id) references supplement (supplement_id) on delete CASCADE,
  constraint supplement_log_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint supplement_log_servings_check check ((servings > (0)::numeric))
) TABLESPACE pg_default;


-- Pre-insert command (supplement_log_id's based on type int)
ALTER TABLE public.supplement_log
ALTER COLUMN supplement_log_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (supplement_log_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.supplement_log', 'supplement_log_id'),
    (SELECT MAX(supplement_log_id) FROM public.supplement_log),
    true
);

-------------------------------------------------------------------
-- depricated --
create table public.users (
  user_id uuid not null default gen_random_uuid (),
  email text not null,
  fname text not null default ''::text,
  lname text not null default ''::text,
  sex text not null default ''::text,
  age integer null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint users_pkey primary key (user_id),
  constraint users_email_key unique (email),
  constraint users_age_check check (
    (
      (age is null)
      or (age >= 0)
    )
  )
) TABLESPACE pg_default;

-------------------------------------------------------------------
-- need to depricate and replace with service worker cache state
create table public.users_logged_in (
  id bigint generated by default as identity not null,
  users_email text not null,
  public_ip text not null,
  is_logged_in boolean not null default true,
  updated_at timestamp with time zone not null default now(),
  constraint users_logged_in_pkey primary key (id),
  constraint users_logged_in_public_ip_key unique (public_ip),
  constraint users_logged_in_users_email_key unique (users_email)
) TABLESPACE pg_default;

-------------------------------------------------------------------
create table public.weight_log (
  weight_log_id bigint generated by default as identity not null,
  user_id uuid not null,
  weight numeric(8, 2) not null,
  bmi numeric(5, 2) null,
  date date not null default CURRENT_DATE,
  constraint weight_log_pkey1 primary key (weight_log_id),
  constraint weight_log_user_id_fkey1 foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint weight_log_weight_check1 check ((weight > (0)::numeric))
) TABLESPACE pg_default;


-- Pre-insert command (weight_log_id's based on type int)
ALTER TABLE public.weight_log
ALTER COLUMN weight_log_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (weight_log_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.weight_log', 'weight_log_id'),
    (SELECT MAX(weight_log_id) FROM public.weight_log),
    true
);


-------------------------------------------------------------------
create table public.workout (
  workout_id bigint generated by default as identity not null,
  user_id uuid not null,
  type text not null,
  average_workout_time integer null,
  calories_burned integer not null default 0,
  share_with_others boolean not null default false,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint workout_pkey primary key (workout_id),
  constraint workout_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint workout_average_workout_time_check check (
    (
      (average_workout_time is null)
      or (average_workout_time >= 0)
    )
  ),
  constraint workout_calories_burned_check check ((calories_burned >= 0))
) TABLESPACE pg_default;

create index IF not exists workout_user_id_idx on public.workout using btree (user_id) TABLESPACE pg_default;

create index IF not exists workout_active_idx on public.workout using btree (is_active) TABLESPACE pg_default;


-- Pre-insert command (workout_id's based on type int)
ALTER TABLE public.workout
ALTER COLUMN workout_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (workout_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.workout', 'workout_id'),
    (SELECT MAX(workout_id) FROM public.workout),
    true
);


-------------------------------------------------------------------
create table public.workout_log (
  workout_log_id bigint generated by default as identity not null,
  workout_id bigint not null,
  user_id uuid not null,
  workout_time integer null,
  calories_burned integer not null default 0,
  date date not null default CURRENT_DATE,
  constraint workout_log_pkey primary key (workout_log_id),
  constraint workout_log_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint workout_log_workout_id_fkey foreign KEY (workout_id) references workout (workout_id) on delete CASCADE,
  constraint workout_log_calories_burned_check check ((calories_burned >= 0)),
  constraint workout_log_workout_time_check check (
    (
      (workout_time is null)
      or (workout_time >= 0)
    )
  )
) TABLESPACE pg_default;



-- Pre-insert command (workout_log_id's based on type int)
ALTER TABLE public.workout_log
ALTER COLUMN workout_log_id SET GENERATED BY DEFAULT;
 
-- Post-insert command (workout_log_id's based on type int)
SELECT setval(
    pg_get_serial_sequence('public.workout_log', 'workout_log_id'),
    (SELECT MAX(workout_log_id) FROM public.workout_log),
    true
);
